### ISSUE TITLE
the Documentation chapter about Firmware retractation is now wrong about Cura. The advised plugin is now available in the Cura MarketPlace!

### ISSUE THREAD

**Issue by altimac** [Guilouz/Klipper-Flsun-Super-Racer#3]
Hi!

Your *excellent* documentation is now partially wrong regarding the installation of the "Klipper Settings Plugin" for Cura as you don't need to hack Cura plugins folder since it's available officially on the Cura MarketPlace (see https://marketplace.ultimaker.com/app/cura/plugins/JJGraphiX/KlipperSettingsPlugin)

thanks.

**Comment by Guilouz** [comment]
Not really, version on Cura MarketPlace is 1.0.1 and latest version on Github is 1.0.2 ^^

**Comment by altimac** [comment]
Good catch, but I suppose it's just a matter of days for the Cura MarketPlace version to be updated...
I think for the sake of simplicity, pointing the user to the official Cura MarketPlace is still a good idea :)
