### ISSUE TITLE
Hotend PID calibration fail: out of range

### ISSUE THREAD

**Issue by brocasm** [Guilouz/Klipper-Flsun-Super-Racer#4]
Au moment de lancer la macro PID HOTEND, j'ai eu l'erreur Move out of range.

La raison: j'ai fait un G91 pour passer en position relatif pour la calibration de l'extrudeur et j'ai pas fait de G90 pour revenir en absolut.

Je propose donc d'ajouter un G90 avant le déplacement dans la macro.

`[gcode_macro PID_HOTEND]
description: PID Hotend
gcode:
  {% if printer.idle_timeout.state == "Printing" %}
  RESPOND TYPE=error MSG="Impossible de lancer cette macro actuellement !"
  {% else %}
  RESPOND MSG="Calibration PID de la buse en cours..."
  G28
  G90
  G1 Z50 F1500
  M400
  M106
  PID_CALIBRATE HEATER=extruder TARGET={params.TEMP|default(220)}
  RESPOND MSG="Calibration PID terminée !  Pensez à sauvegarder la configuration !"
  M107
  G28
  {% endif %}`

**Comment by brocasm** [comment]
Même problématique et proposition pour le PID_BED

**Comment by Guilouz** [comment]
C'est fait ;)
